# Generated by Django 3.1.6 on 2021-05-02 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screendisplay', '0003_auto_20210103_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=150, verbose_name='नाम')),
                ('office_sec_name', models.CharField(max_length=50, verbose_name='नाम')),
                ('office_website', models.CharField(max_length=50, verbose_name='वेबसाइट')),
                ('office_email', models.CharField(max_length=150, verbose_name='इमेल')),
                ('office_phoneno', models.CharField(max_length=50, verbose_name='फोन नं.')),
                ('office_emergencyno', models.CharField(max_length=50, verbose_name='अन्य आपतकालीन नं.')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('office_image', models.ImageField(upload_to='office_uploaded_image', verbose_name='फोटो')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
